trigger:
  branches:
    include:
      - main

variables:
  - group: <your-variable-group-name>
  - name: IMAGE_TAG
    value: $(Build.BuildId)

stages:
  - stage: Build
    displayName: Build and Push Image
    jobs:
      - job: Build
        displayName: Build and Push Image
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Checkout@1

          # Login to ACR
          - task: AzureCLI@2
            inputs:
              azureSubscription: '<Azure-Service-Connection>'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az acr login --name $(ACR_NAME)

          # Build and Push Docker Image
          - task: Docker@2
            displayName: Build and Push Docker Image
            inputs:
              command: buildAndPush
              repository: $(ACR_NAME)/$(IMAGE_NAME)
              dockerfile: Dockerfile
              containerRegistry: '<Azure-Container-Registry-Service-Connection>'
              tags: $(IMAGE_TAG)

  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
      - job: Deploy
        displayName: Deploy Application
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # Replace image tag in deployment.yaml
          - task: KubernetesManifest@0
            displayName: Deploy to AKS
            inputs:
              action: 'deploy'
              manifests: |
                manifests/deployment.yaml
                manifests/service.yaml
                manifests/hpa.yaml
                manifests/configmap.yaml
              containers: |
                $(ACR_NAME)/$(IMAGE_NAME):$(IMAGE_TAG)
              namespace: 'default'
